FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app
EXPOSE 8080

# Copy csproj and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy everything else
COPY . ./

# Run with hot reload
ENTRYPOINT ["dotnet", "watch", "run", "--no-restore", "--urls", "http://0.0.0.0:8080"]
